import { defineStackbitConfig } from '@stackbit/types'
import { GitContentSource } from '@stackbit/cms-git'

function colorSchemeEnumField(name: string, group?: string) {
  return {
    name,
    type: 'enum' as const,
    label: 'Color Scheme',
    /** Non-required enums show a “None” option in the visual editor; clearing breaks our Zod pipeline. */
    required: true,
    options: [
      { label: 'Soft', value: 'soft' },
      { label: 'Bright', value: 'bright' },
      { label: 'Wine', value: 'wine' },
    ],
    default: 'soft',
    ...(group ? { group } : {}),
  }
}

function heroColorSchemeField() {
  return {
    name: 'heroColorScheme',
    type: 'enum' as const,
    label: 'Color Scheme',
    required: true,
    options: [
      { label: 'Clear', value: 'clear' },
      { label: 'Wine', value: 'wine' },
    ],
    default: 'wine',
    group: 'hero',
  }
}

export default defineStackbitConfig({
  stackbitVersion: '~0.6.0',
  ssgName: 'custom',
  nodeVersion: '22',
  contentSources: [
    new GitContentSource({
      rootPath: __dirname,
      contentDirs: ['content'],
      assetsConfig: {
        referenceType: 'static',
        staticDir: 'public',
        uploadDir: 'images',
        publicPath: '/',
      },
      models: [
        {
          name: 'HomePage',
          type: 'page',
          urlPath: '/',
          filePath: 'content/home/data.md',
          fieldGroups: [
            { name: 'hero', label: 'Hero' },
            { name: 'imageTextAbout', label: 'Image + Text' },
            { name: 'mediaGrid', label: 'Media Grid' },
            { name: 'imageTextFeature', label: 'Image + Text' },
            { name: 'quoteBanner', label: 'Quote Banner' },
          ],
          fields: [
            { name: 'headerBrandLine1', type: 'string', label: 'Header - Brand line 1' },
            { name: 'headerBrandLine2', type: 'string', label: 'Header - Brand line 2' },
            {
              name: 'headerNavLinks',
              type: 'list',
              label: 'Header - Navigation Links',
              items: { type: 'text' },
            },
            heroColorSchemeField(),
            { name: 'heroTitle', type: 'string', label: 'Title', group: 'hero' },
            { name: 'heroSubtitle', type: 'string', label: 'Subtitle', group: 'hero' },
            { name: 'heroTagline', type: 'string', label: 'Eyebrow', group: 'hero' },
            { name: 'heroImage', type: 'image', label: 'Background image', group: 'hero' },
            { name: 'heroImageAlt', type: 'string', label: 'Image alt', group: 'hero' },
            { name: 'primaryCtaLabel', type: 'string', label: 'Primary CTA label', group: 'hero' },
            { name: 'primaryCtaHref', type: 'string', label: 'Primary CTA URL', group: 'hero' },
            { name: 'secondaryCtaLabel', type: 'string', label: 'Secondary CTA label', group: 'hero' },
            { name: 'secondaryCtaHref', type: 'string', label: 'Secondary CTA URL', group: 'hero' },
            colorSchemeEnumField('aboutSurface', 'imageTextAbout'),
            { name: 'aboutEyebrow', type: 'string', label: 'Eyebrow', group: 'imageTextAbout' },
            { name: 'aboutTitle', type: 'string', label: 'Title', group: 'imageTextAbout' },
            { name: 'aboutText', type: 'text', label: 'Body', group: 'imageTextAbout' },
            { name: 'aboutImage', type: 'image', label: 'Image', group: 'imageTextAbout' },
            { name: 'aboutImageAlt', type: 'string', label: 'Image alt', group: 'imageTextAbout' },
            { name: 'aboutLinkText', type: 'string', label: 'Link text', group: 'imageTextAbout' },
            { name: 'aboutHref', type: 'string', label: 'Link URL', group: 'imageTextAbout' },
            colorSchemeEnumField('mediaGridColorScheme', 'mediaGrid'),
            { name: 'mediaEyebrow', type: 'string', label: 'Eyebrow', group: 'mediaGrid' },
            { name: 'mediaTitle', type: 'string', label: 'Title', group: 'mediaGrid' },
            colorSchemeEnumField('featureSurface', 'imageTextFeature'),
            { name: 'featureEyebrow', type: 'string', label: 'Eyebrow', group: 'imageTextFeature' },
            { name: 'featureTitle', type: 'string', label: 'Title', group: 'imageTextFeature' },
            { name: 'featureText', type: 'text', label: 'Body', group: 'imageTextFeature' },
            { name: 'featureImage', type: 'image', label: 'Image', group: 'imageTextFeature' },
            { name: 'featureImageAlt', type: 'string', label: 'Image alt', group: 'imageTextFeature' },
            { name: 'featureCtaLabel', type: 'string', label: 'CTA label', group: 'imageTextFeature' },
            { name: 'featureCtaHref', type: 'string', label: 'CTA URL', group: 'imageTextFeature' },
            colorSchemeEnumField('quoteBannerColorScheme', 'quoteBanner'),
            { name: 'quoteText', type: 'text', label: 'Quote', group: 'quoteBanner' },
            { name: 'quoteAuthor', type: 'string', label: 'Author', group: 'quoteBanner' },
            { name: 'quoteImage', type: 'image', label: 'Background image', group: 'quoteBanner' },
            { name: 'quoteImageAlt', type: 'string', label: 'Image alt', group: 'quoteBanner' },
            { name: 'footerBrandLine1', type: 'string', label: 'Footer - Brand line 1' },
            { name: 'footerBrandLine2', type: 'string', label: 'Footer - Brand line 2' },
            { name: 'footerBrandTagline', type: 'text', label: 'Footer - Tagline' },
            {
              name: 'footerNavLinks',
              type: 'list',
              label: 'Footer - Navigation Links',
              items: { type: 'text' },
            },
            { name: 'instagramUrl', type: 'string', label: 'Footer - Social - Instagram URL' },
            { name: 'youtubeUrl', type: 'string', label: 'Footer - Social - YouTube URL' },
            { name: 'facebookUrl', type: 'string', label: 'Footer - Social - Facebook URL' },
            { name: 'email', type: 'string', label: 'Footer - Contact Email' },
          ],
        },
        {
          name: 'AboutPage',
          type: 'page',
          urlPath: '/about',
          filePath: 'content/about/page.md',
          fieldGroups: [
            { name: 'imageBigText', label: 'Image + Big Text' },
            { name: 'statsRow', label: 'Stats Row' },
            { name: 'richtextContent', label: 'Richtext Content' },
            { name: 'timeline', label: 'Timeline' },
            { name: 'textButtons', label: 'Text + Buttons' },
          ],
          fields: [
            colorSchemeEnumField('heroColorScheme', 'imageBigText'),
            { name: 'heroEyebrow', type: 'string', label: 'Eyebrow', group: 'imageBigText' },
            { name: 'heroTitleLine1', type: 'string', label: 'Title line 1', group: 'imageBigText' },
            { name: 'heroTitleAccent', type: 'string', label: 'Accent word', group: 'imageBigText' },
            { name: 'heroTitleLine2', type: 'string', label: 'Title line 2', group: 'imageBigText' },
            { name: 'heroIntro', type: 'text', label: 'Intro', group: 'imageBigText' },
            { name: 'heroImage', type: 'image', label: 'Portrait (optional; uses home About image if empty)', group: 'imageBigText' },
            { name: 'heroImageAlt', type: 'string', label: 'Image alt', group: 'imageBigText' },
            { name: 'heroQuote', type: 'text', label: 'Quote', group: 'imageBigText' },
            { name: 'heroQuoteAttribution', type: 'string', label: 'Quote attribution', group: 'imageBigText' },
            colorSchemeEnumField('statsSurface', 'statsRow'),
            { name: 'highlights', type: 'list', label: 'Highlights', items: { type: 'object', fields: [{ name: 'number', type: 'string', label: 'Number' }, { name: 'label', type: 'string', label: 'Label' }] }, group: 'statsRow' },
            colorSchemeEnumField('fullBioColorScheme', 'richtextContent'),
            { name: 'fullBioEyebrow', type: 'string', label: 'Eyebrow', group: 'richtextContent' },
            { name: 'fullBioParagraphs', type: 'list', label: 'Paragraphs', items: { type: 'text' }, group: 'richtextContent' },
            colorSchemeEnumField('timelineColorScheme', 'timeline'),
            { name: 'timelineSectionEyebrow', type: 'string', label: 'Eyebrow', group: 'timeline' },
            { name: 'timelineSectionTitle', type: 'string', label: 'Heading', group: 'timeline' },
            { name: 'timeline', type: 'list', label: 'Milestones', items: { type: 'object', fields: [{ name: 'year', type: 'string', label: 'Year' }, { name: 'title', type: 'string', label: 'Title' }, { name: 'description', type: 'markdown', label: 'Body (Markdown)' }] }, group: 'timeline' },
            colorSchemeEnumField('ctaColorScheme', 'textButtons'),
            { name: 'ctaTitleLine1', type: 'string', label: 'Title line 1', group: 'textButtons' },
            { name: 'ctaTitleLine2', type: 'string', label: 'Title line 2', group: 'textButtons' },
            { name: 'ctaPrimaryLabel', type: 'string', label: 'Primary button', group: 'textButtons' },
            { name: 'ctaPrimaryHref', type: 'string', label: 'Primary URL', group: 'textButtons' },
            { name: 'ctaSecondaryLabel', type: 'string', label: 'Secondary button', group: 'textButtons' },
            { name: 'ctaSecondaryHref', type: 'string', label: 'Secondary URL', group: 'textButtons' },
          ],
        },
        {
          name: 'ProductionsPage',
          type: 'page',
          urlPath: '/productions',
          filePath: 'content/productions-landing/page.md',
          fieldGroups: [
            { name: 'pageHero', label: 'Page Hero' },
            { name: 'imageTextCards', label: 'Image + Text Cards' },
          ],
          fields: [
            colorSchemeEnumField('pageHeroColorScheme', 'pageHero'),
            { name: 'heroEyebrow', type: 'string', label: 'Eyebrow', group: 'pageHero' },
            { name: 'heroTitle', type: 'string', label: 'Title', group: 'pageHero' },
            { name: 'heroIntro', type: 'text', label: 'Intro', group: 'pageHero' },
            colorSchemeEnumField('productionsListColorScheme', 'imageTextCards'),
          ],
        },
        {
          name: 'GalleryPage',
          type: 'page',
          urlPath: '/gallery',
          filePath: 'content/gallery-landing/page.md',
          fieldGroups: [
            { name: 'pageHero', label: 'Page Hero' },
            { name: 'tabItems', label: 'Tab Items' },
          ],
          fields: [
            colorSchemeEnumField('pageHeroColorScheme', 'pageHero'),
            { name: 'heroEyebrow', type: 'string', label: 'Eyebrow', group: 'pageHero' },
            { name: 'heroTitle', type: 'string', label: 'Title', group: 'pageHero' },
            colorSchemeEnumField('tabItemsColorScheme', 'tabItems'),
            { name: 'filterCategories', type: 'list', label: 'Categories (first should be “All”)', items: { type: 'string' }, group: 'tabItems' },
          ],
        },
        {
          name: 'ContactPage',
          type: 'page',
          urlPath: '/contact',
          filePath: 'content/contact/page.md',
          fieldGroups: [
            { name: 'pageHero', label: 'Page Hero' },
            { name: 'contactForm', label: 'Contact Form' },
          ],
          fields: [
            colorSchemeEnumField('pageHeroColorScheme', 'pageHero'),
            { name: 'heroEyebrow', type: 'string', label: 'Eyebrow', group: 'pageHero' },
            { name: 'heroTitle', type: 'string', label: 'Title', group: 'pageHero' },
            colorSchemeEnumField('contactFormColorScheme', 'contactForm'),
            { name: 'introHeading', type: 'string', label: 'Heading', group: 'contactForm' },
            { name: 'introBody', type: 'text', label: 'Body', group: 'contactForm' },
            { name: 'directEmailLabel', type: 'string', label: 'Email label', group: 'contactForm' },
            { name: 'email', type: 'string', label: 'Address', group: 'contactForm' },
            { name: 'socialChannelsLabel', type: 'string', label: 'Social heading', group: 'contactForm' },
            { name: 'instagramUrl', type: 'string', label: 'Instagram URL', group: 'contactForm' },
            { name: 'instagramHandle', type: 'string', label: 'Instagram display', group: 'contactForm' },
            { name: 'youtubeUrl', type: 'string', label: 'YouTube URL', group: 'contactForm' },
            { name: 'youtubeHandle', type: 'string', label: 'YouTube display', group: 'contactForm' },
            { name: 'facebookUrl', type: 'string', label: 'Facebook URL', group: 'contactForm' },
            { name: 'facebookHandle', type: 'string', label: 'Facebook display', group: 'contactForm' },
            { name: 'successTitle', type: 'string', label: 'Success title', group: 'contactForm' },
            { name: 'successMessage', type: 'text', label: 'Success message', group: 'contactForm' },
            { name: 'successResetLabel', type: 'string', label: 'Reset link text', group: 'contactForm' },
          ],
        },
        {
          name: 'GalleryItem',
          type: 'data',
          folder: 'content/gallery',
          fields: [
            { name: 'title', type: 'string', label: 'Title' },
            { name: 'image', type: 'string', label: 'Image URL' },
            { name: 'alt', type: 'string', label: 'Alt Text (accessibility)' },
            { name: 'category', type: 'string', label: 'Category (Performance / Behind the Scenes)' },
            { name: 'order', type: 'number', label: 'Display Order' },
          ],
        },
        {
          name: 'video',
          type: 'data',
          folder: 'content/media',
          fields: [
            { name: 'title', type: 'string', label: 'Title' },
            { name: 'type', type: 'enum', options: ['video', 'image'], label: 'Type' },
            { name: 'videoUrl', type: 'string', label: 'Video - YouTube Embed URL' },
            { name: 'thumbnail', type: 'string', label: 'Thumbnail Image URL' },
            { name: 'description', type: 'string', label: 'Short Description' },
            { name: 'order', type: 'number', label: 'Display Order' },
          ],
        },
        {
          name: 'image',
          type: 'data',
          folder: 'content/media',
          fields: [
            { name: 'title', type: 'string', label: 'Title' },
            { name: 'type', type: 'enum', options: ['video', 'image'], label: 'Type' },
            { name: 'videoUrl', type: 'string', label: 'Video - YouTube Embed URL' },
            { name: 'thumbnail', type: 'string', label: 'Thumbnail Image URL' },
            { name: 'description', type: 'string', label: 'Short Description' },
            { name: 'order', type: 'number', label: 'Display Order' },
          ],
        },
        {
          name: 'Production',
          type: 'data',
          folder: 'content/productions',
          fields: [
            { name: 'title', type: 'string', label: 'Opera Title' },
            { name: 'role', type: 'string', label: 'Role / Character' },
            { name: 'venue', type: 'string', label: 'Venue & City' },
            { name: 'year', type: 'string', label: 'Year' },
            { name: 'image', type: 'string', label: 'Production Image URL' },
            { name: 'description', type: 'text', label: 'Description' },
            { name: 'tags', type: 'list', items: { type: 'string' }, label: 'Tags' },
          ],
        },
        {
          name: 'Education',
          type: 'data',
          folder: 'content/education',
          fields: [
            { name: 'school', type: 'string', label: 'School' },
            { name: 'summary', type: 'string', label: 'Summary' },
            { name: 'startDate', type: 'string', label: 'Start Date' },
            { name: 'endDate', type: 'string', label: 'End Date' },
            { name: 'tags', type: 'list', items: { type: 'string' }, label: 'Tags' },
          ],
        },
      ],
    }),
  ],
})
