import { defineStackbitConfig } from '@stackbit/types'
import { GitContentSource } from '@stackbit/cms-git'

function colorSchemeEnumField(name: string, group?: string) {
  return {
    name,
    type: 'enum' as const,
    label: 'Color Scheme',
    /** Non-required enums show a “None” option in the visual editor; clearing breaks our Zod pipeline. */
    required: true,
    options: [
      { label: 'Soft', value: 'soft' },
      { label: 'Bright', value: 'bright' },
      { label: 'Wine', value: 'wine' },
    ],
    default: 'soft',
    ...(group ? { group } : {}),
  }
}

function slideInField(name: string, group?: string) {
  return {
    name,
    type: 'boolean' as const,
    label: 'Slide In Animation',
    default: true,
    ...(group ? { group } : {}),
  }
}

function heroColorSchemeField() {
  return {
    name: 'heroColorScheme',
    type: 'enum' as const,
    label: 'Color Scheme',
    required: true,
    options: [
      { label: 'Clear', value: 'clear' },
      { label: 'Wine', value: 'wine' },
    ],
    default: 'wine',
    group: 'hero',
  }
}

export default defineStackbitConfig({
  stackbitVersion: '~0.6.0',
  ssgName: 'custom',
  nodeVersion: '22',
  contentSources: [
    new GitContentSource({
      rootPath: __dirname,
      contentDirs: ['content'],
      assetsConfig: {
        referenceType: 'static',
        staticDir: 'public',
        uploadDir: 'images',
        publicPath: '/',
      },
      models: [
        {
          name: 'HomePage',
          type: 'page',
          urlPath: '/',
          filePath: 'content/home/data.md',
          fieldGroups: [
            { name: 'hero', label: 'Hero' },
            { name: 'imageTextAbout', label: 'Image + Text' },
            { name: 'organizationsStrip', label: 'Organizations Strip' },
            { name: 'mediaGrid', label: 'Media Grid' },
            { name: 'splitGrid', label: 'Split Grid' },
            { name: 'quoteBanner', label: 'Quote Banner' },
          ],
          fields: [
            { name: 'headerBrandLine1', type: 'string', label: 'Header - Brand line 1' },
            { name: 'headerBrandLine2', type: 'string', label: 'Header - Brand line 2' },
            {
              name: 'headerNavLinks',
              type: 'list',
              label: 'Header - Navigation Links',
              items: {
                type: 'object',
                fields: [
                  { name: 'label', type: 'string', label: 'Label' },
                  { name: 'href', type: 'string', label: 'URL' },
                ],
              },
            },
            heroColorSchemeField(),
            { name: 'heroTitle', type: 'string', label: 'Title', group: 'hero' },
            { name: 'heroSubtitle', type: 'string', label: 'Subtitle', group: 'hero' },
            { name: 'heroTagline', type: 'string', label: 'Eyebrow', group: 'hero' },
            { name: 'heroImage', type: 'image', label: 'Background image', group: 'hero' },
            { name: 'heroImageAlt', type: 'string', label: 'Image alt', group: 'hero' },
            { name: 'primaryCtaLabel', type: 'string', label: 'Primary CTA label', group: 'hero' },
            { name: 'primaryCtaHref', type: 'string', label: 'Primary CTA URL', group: 'hero' },
            { name: 'secondaryCtaLabel', type: 'string', label: 'Secondary CTA label', group: 'hero' },
            { name: 'secondaryCtaHref', type: 'string', label: 'Secondary CTA URL', group: 'hero' },
            colorSchemeEnumField('aboutSurface', 'imageTextAbout'),
            slideInField('aboutSlideIn', 'imageTextAbout'),
            { name: 'aboutEyebrow', type: 'string', label: 'Eyebrow', group: 'imageTextAbout' },
            { name: 'aboutTitle', type: 'string', label: 'Title', group: 'imageTextAbout' },
            { name: 'aboutText', type: 'text', label: 'Body', group: 'imageTextAbout' },
            { name: 'aboutImage', type: 'image', label: 'Image', group: 'imageTextAbout' },
            { name: 'aboutImageAlt', type: 'string', label: 'Image alt', group: 'imageTextAbout' },
            { name: 'aboutLinkText', type: 'string', label: 'Link text', group: 'imageTextAbout' },
            { name: 'aboutHref', type: 'string', label: 'Link URL', group: 'imageTextAbout' },
            colorSchemeEnumField('organizationsStripColorScheme', 'organizationsStrip'),
            slideInField('organizationsStripSlideIn', 'organizationsStrip'),
            {
              name: 'organizationsStripEyebrow',
              type: 'string',
              label: 'Eyebrow',
              group: 'organizationsStrip',
            },
            {
              name: 'organizationsStripTitle',
              type: 'string',
              label: 'Title',
              group: 'organizationsStrip',
            },
            {
              name: 'organizationsStripDescription',
              type: 'text',
              label: 'Description',
              group: 'organizationsStrip',
            },
            {
              name: 'organizationsStripLinkText',
              type: 'string',
              label: 'Link text',
              group: 'organizationsStrip',
            },
            {
              name: 'organizationsStripItems',
              type: 'list',
              label: 'Featured organizations (slugs)',
              group: 'organizationsStrip',
              items: { type: 'string' },
            },
            colorSchemeEnumField('mediaGridColorScheme', 'mediaGrid'),
            slideInField('mediaGridSlideIn', 'mediaGrid'),
            { name: 'mediaEyebrow', type: 'string', label: 'Eyebrow', group: 'mediaGrid' },
            { name: 'mediaTitle', type: 'string', label: 'Title', group: 'mediaGrid' },
            {
              name: 'mediaItems',
              type: 'list',
              label: 'Media Items',
              group: 'mediaGrid',
              items: {
                type: 'reference',
                models: ['video', 'image'],
              },
            },
            colorSchemeEnumField('splitGridColorScheme', 'splitGrid'),
            slideInField('splitGridSlideIn', 'splitGrid'),
            { name: 'splitGridTitle', type: 'string', label: 'Title', group: 'splitGrid' },
            { name: 'splitGridDescription', type: 'text', label: 'Description', group: 'splitGrid' },
            {
              name: 'splitGridItems',
              type: 'list',
              label: 'Items',
              group: 'splitGrid',
              items: {
                type: 'object',
                fields: [
                  { name: 'href', type: 'string', label: 'URL' },
                  { name: 'image', type: 'image', label: 'Background image' },
                  {
                    name: 'badges',
                    type: 'list',
                    label: 'Labels (max 4)',
                    items: { type: 'string' },
                  },
                  { name: 'title', type: 'string', label: 'Title' },
                  { name: 'subtitle', type: 'string', label: 'Subtitle' },
                ],
              },
            },
            colorSchemeEnumField('quoteBannerColorScheme', 'quoteBanner'),
            slideInField('quoteBannerSlideIn', 'quoteBanner'),
            { name: 'quoteText', type: 'text', label: 'Quote', group: 'quoteBanner' },
            { name: 'quoteAuthor', type: 'string', label: 'Author', group: 'quoteBanner' },
            { name: 'quoteImage', type: 'image', label: 'Background image', group: 'quoteBanner' },
            { name: 'quoteImageAlt', type: 'string', label: 'Image alt', group: 'quoteBanner' },
            {
              name: 'quoteImageCredit',
              type: 'object',
              label: 'Image credit (optional)',
              group: 'quoteBanner',
              fields: [
                { name: 'author', type: 'string', label: 'Photographer name' },
                { name: 'authorUrl', type: 'string', label: 'Photographer URL' },
                { name: 'source', type: 'string', label: 'Source label (default: Unsplash)' },
                { name: 'sourceUrl', type: 'string', label: 'Photo URL on source' },
              ],
            },
            { name: 'footerBrandLine1', type: 'string', label: 'Footer - Brand line 1' },
            { name: 'footerBrandLine2', type: 'string', label: 'Footer - Brand line 2' },
            { name: 'footerBrandTagline', type: 'text', label: 'Footer - Tagline' },
            {
              name: 'footerNavLinks',
              type: 'list',
              label: 'Footer - Navigation Links',
              items: {
                type: 'object',
                fields: [
                  { name: 'label', type: 'string', label: 'Label' },
                  { name: 'href', type: 'string', label: 'URL' },
                ],
              },
            },
            { name: 'instagramUrl', type: 'string', label: 'Footer - Social - Instagram URL' },
            { name: 'youtubeUrl', type: 'string', label: 'Footer - Social - YouTube URL' },
            { name: 'facebookUrl', type: 'string', label: 'Footer - Social - Facebook URL' },
            { name: 'muvacUrl', type: 'string', label: 'Footer - Social - Muvac URL' },
            { name: 'email', type: 'string', label: 'Footer - Contact Email' },
          ],
        },
        {
          name: 'BioPage',
          type: 'page',
          urlPath: '/bio',
          filePath: 'content/bio/page.md',
          fieldGroups: [
            { name: 'pageHero', label: 'Page Hero' },
            { name: 'richtextContent', label: 'Richtext Content' },
          ],
          fields: [
            colorSchemeEnumField('pageHeroColorScheme', 'pageHero'),
            { name: 'heroEyebrow', type: 'string', label: 'Eyebrow', group: 'pageHero' },
            { name: 'heroTitle', type: 'string', label: 'Title', group: 'pageHero' },
            { name: 'heroDescription', type: 'text', label: 'Description', group: 'pageHero' },
            colorSchemeEnumField('fullBioColorScheme', 'richtextContent'),
            slideInField('fullBioSlideIn', 'richtextContent'),
            { name: 'fullBioEyebrow', type: 'string', label: 'Eyebrow', group: 'richtextContent' },
            {
              name: 'fullBioParagraphs',
              type: 'list',
              label: 'Paragraphs',
              group: 'richtextContent',
              items: {
                type: 'object',
                fields: [
                  { name: 'content', type: 'markdown', label: 'Paragraph markdown' },
                  { name: 'addBorderBottom', type: 'boolean', label: 'Add Border Bottom' },
                ],
              },
            },
            { name: 'fullBioImage', type: 'image', label: 'Side image (optional; leave empty for centered text)', group: 'richtextContent' },
            { name: 'fullBioImageAlt', type: 'string', label: 'Side image alt', group: 'richtextContent' },
            {
              name: 'fullBioImagePosition',
              type: 'enum',
              label: 'Side image position',
              options: [
                { label: 'Right', value: 'right' },
                { label: 'Left', value: 'left' },
              ],
              default: 'right',
              group: 'richtextContent',
            },
          ],
        },
        {
          name: 'CareerPage',
          type: 'page',
          urlPath: '/career',
          filePath: 'content/career/page.md',
          fieldGroups: [
            { name: 'imageBigText', label: 'Image + Big Text' },
            { name: 'statsRow', label: 'Stats Row' },
            { name: 'timeline', label: 'Timeline' },
            { name: 'textButtons', label: 'Text + Buttons' },
          ],
          fields: [
            colorSchemeEnumField('heroColorScheme', 'imageBigText'),
            slideInField('heroSlideIn', 'imageBigText'),
            { name: 'heroEyebrow', type: 'string', label: 'Eyebrow', group: 'imageBigText' },
            { name: 'heroTitleLine1', type: 'string', label: 'Title line 1', group: 'imageBigText' },
            { name: 'heroTitleAccent', type: 'string', label: 'Accent word', group: 'imageBigText' },
            { name: 'heroTitleLine2', type: 'string', label: 'Title line 2', group: 'imageBigText' },
            { name: 'heroIntro', type: 'text', label: 'Intro', group: 'imageBigText' },
            { name: 'heroImage', type: 'image', label: 'Portrait (optional; uses home About image if empty)', group: 'imageBigText' },
            { name: 'heroImageAlt', type: 'string', label: 'Image alt', group: 'imageBigText' },
            { name: 'heroQuote', type: 'text', label: 'Quote', group: 'imageBigText' },
            { name: 'heroQuoteAttribution', type: 'string', label: 'Quote attribution', group: 'imageBigText' },
            colorSchemeEnumField('statsSurface', 'statsRow'),
            slideInField('statsSlideIn', 'statsRow'),
            { name: 'highlights', type: 'list', label: 'Highlights', items: { type: 'object', fields: [{ name: 'number', type: 'string', label: 'Number' }, { name: 'label', type: 'string', label: 'Label' }] }, group: 'statsRow' },
            colorSchemeEnumField('timelineColorScheme', 'timeline'),
            slideInField('timelineSlideIn', 'timeline'),
            { name: 'timelineSectionEyebrow', type: 'string', label: 'Eyebrow', group: 'timeline' },
            { name: 'timelineSectionTitle', type: 'string', label: 'Heading', group: 'timeline' },
            { name: 'timeline', type: 'list', label: 'Milestones', items: { type: 'object', fields: [{ name: 'year', type: 'string', label: 'Year' }, { name: 'title', type: 'string', label: 'Title' }, { name: 'description', type: 'markdown', label: 'Body (Markdown)' }] }, group: 'timeline' },
            colorSchemeEnumField('ctaColorScheme', 'textButtons'),
            slideInField('ctaSlideIn', 'textButtons'),
            { name: 'ctaTitleLine1', type: 'string', label: 'Title line 1', group: 'textButtons' },
            { name: 'ctaTitleLine2', type: 'string', label: 'Title line 2', group: 'textButtons' },
            { name: 'ctaPrimaryLabel', type: 'string', label: 'Primary button', group: 'textButtons' },
            { name: 'ctaPrimaryHref', type: 'string', label: 'Primary URL', group: 'textButtons' },
            { name: 'ctaSecondaryLabel', type: 'string', label: 'Secondary button', group: 'textButtons' },
            { name: 'ctaSecondaryHref', type: 'string', label: 'Secondary URL', group: 'textButtons' },
          ],
        },
        {
          name: 'RolesPage',
          type: 'page',
          urlPath: '/roles',
          filePath: 'content/roles-landing/page.md',
          fieldGroups: [
            { name: 'pageHero', label: 'Page Hero' },
            { name: 'rolesIndex', label: 'Roles List' },
          ],
          fields: [
            colorSchemeEnumField('pageHeroColorScheme', 'pageHero'),
            { name: 'heroEyebrow', type: 'string', label: 'Eyebrow', group: 'pageHero' },
            { name: 'heroTitle', type: 'string', label: 'Title', group: 'pageHero' },
            { name: 'heroDescription', type: 'text', label: 'Description', group: 'pageHero' },
            colorSchemeEnumField('rolesListColorScheme', 'rolesIndex'),
            slideInField('rolesListSlideIn', 'rolesIndex'),
          ],
        },
        {
          name: 'OrganizationsPage',
          type: 'page',
          urlPath: '/organizations',
          filePath: 'content/organizations-landing/page.md',
          fieldGroups: [
            { name: 'pageHero', label: 'Page Hero' },
            { name: 'organizationsIndex', label: 'Organizations List' },
          ],
          fields: [
            colorSchemeEnumField('pageHeroColorScheme', 'pageHero'),
            { name: 'heroEyebrow', type: 'string', label: 'Eyebrow', group: 'pageHero' },
            { name: 'heroTitle', type: 'string', label: 'Title', group: 'pageHero' },
            { name: 'heroDescription', type: 'text', label: 'Description', group: 'pageHero' },
            colorSchemeEnumField('organizationsListColorScheme', 'organizationsIndex'),
            slideInField('organizationsListSlideIn', 'organizationsIndex'),
          ],
        },
        {
          name: 'SchedulePage',
          type: 'page',
          urlPath: '/schedule',
          filePath: 'content/schedule-landing/page.md',
          fieldGroups: [
            { name: 'pageHero', label: 'Page Hero' },
            { name: 'upcoming', label: 'Upcoming' },
            { name: 'past', label: 'Past' },
          ],
          fields: [
            colorSchemeEnumField('pageHeroColorScheme', 'pageHero'),
            { name: 'heroEyebrow', type: 'string', label: 'Eyebrow', group: 'pageHero' },
            { name: 'heroTitle', type: 'string', label: 'Title', group: 'pageHero' },
            { name: 'heroDescription', type: 'text', label: 'Description', group: 'pageHero' },
            colorSchemeEnumField('upcomingColorScheme', 'upcoming'),
            slideInField('upcomingSlideIn', 'upcoming'),
            colorSchemeEnumField('pastColorScheme', 'past'),
            slideInField('pastSlideIn', 'past'),
          ],
        },
        {
          name: 'GalleryPage',
          type: 'page',
          urlPath: '/gallery',
          filePath: 'content/gallery-landing/page.md',
          fieldGroups: [
            { name: 'pageHero', label: 'Page Hero' },
            { name: 'tabItems', label: 'Tab Items' },
          ],
          fields: [
            colorSchemeEnumField('pageHeroColorScheme', 'pageHero'),
            { name: 'heroEyebrow', type: 'string', label: 'Eyebrow', group: 'pageHero' },
            { name: 'heroTitle', type: 'string', label: 'Title', group: 'pageHero' },
            colorSchemeEnumField('tabItemsColorScheme', 'tabItems'),
            slideInField('tabItemsSlideIn', 'tabItems'),
            { name: 'filterCategories', type: 'list', label: 'Categories (first should be “All”)', items: { type: 'string' }, group: 'tabItems' },
          ],
        },
        {
          name: 'ContactPage',
          type: 'page',
          urlPath: '/contact',
          filePath: 'content/contact/page.md',
          fieldGroups: [
            { name: 'pageHero', label: 'Page Hero' },
            { name: 'contactForm', label: 'Contact Form' },
          ],
          fields: [
            colorSchemeEnumField('pageHeroColorScheme', 'pageHero'),
            { name: 'heroEyebrow', type: 'string', label: 'Eyebrow', group: 'pageHero' },
            { name: 'heroTitle', type: 'string', label: 'Title', group: 'pageHero' },
            colorSchemeEnumField('contactFormColorScheme', 'contactForm'),
            slideInField('contactFormSlideIn', 'contactForm'),
            { name: 'introHeading', type: 'string', label: 'Heading', group: 'contactForm' },
            { name: 'introBody', type: 'text', label: 'Body', group: 'contactForm' },
            { name: 'directEmailLabel', type: 'string', label: 'Email label', group: 'contactForm' },
            { name: 'email', type: 'string', label: 'Address', group: 'contactForm' },
            { name: 'socialChannelsLabel', type: 'string', label: 'Social heading', group: 'contactForm' },
            { name: 'instagramUrl', type: 'string', label: 'Instagram URL', group: 'contactForm' },
            { name: 'instagramHandle', type: 'string', label: 'Instagram display', group: 'contactForm' },
            { name: 'youtubeUrl', type: 'string', label: 'YouTube URL', group: 'contactForm' },
            { name: 'youtubeHandle', type: 'string', label: 'YouTube display', group: 'contactForm' },
            { name: 'facebookUrl', type: 'string', label: 'Facebook URL', group: 'contactForm' },
            { name: 'facebookHandle', type: 'string', label: 'Facebook display', group: 'contactForm' },
            { name: 'muvacUrl', type: 'string', label: 'Muvac URL', group: 'contactForm' },
            { name: 'muvacHandle', type: 'string', label: 'Muvac display', group: 'contactForm' },
            { name: 'formSubjectOptions', type: 'list', label: 'Form subject options', items: { type: 'string' }, group: 'contactForm' },
            { name: 'successTitle', type: 'string', label: 'Form success title', group: 'contactForm' },
            { name: 'successMessage', type: 'text', label: 'Form success message', group: 'contactForm' },
            { name: 'successResetLabel', type: 'string', label: 'Form reset link text', group: 'contactForm' },
          ],
        },
        {
          name: 'GalleryItem',
          type: 'data',
          folder: 'content/gallery',
          fields: [
            { name: 'title', type: 'string', label: 'Title' },
            { name: 'image', type: 'string', label: 'Image URL' },
            { name: 'alt', type: 'string', label: 'Alt Text (accessibility)' },
            { name: 'category', type: 'string', label: 'Category (Performance / Behind the Scenes)' },
            { name: 'order', type: 'number', label: 'Display Order' },
            {
              name: 'featuredImg',
              type: 'boolean',
              label: 'Featured image (spans 2 columns on desktop)',
              default: false,
            },
            {
              name: 'roleSlug',
              type: 'string',
              label: 'Role slug (links photo to /roles/…)',
            },
            {
              name: 'gallerySlug',
              type: 'string',
              label: 'Gallery slug (links photo to past /schedule/… without a role)',
            },
          ],
        },
        {
          name: 'video',
          type: 'data',
          folder: 'content/media',
          fields: [
            { name: 'title', type: 'string', label: 'Title' },
            { name: 'type', type: 'enum', options: ['video', 'image'], label: 'Type' },
            { name: 'videoUrl', type: 'string', label: 'Video - YouTube URL' },
            { name: 'imageUrl', type: 'string', label: 'Image - Link URL (opens in new tab)' },
            {
              name: 'thumbnail',
              type: 'string',
              label: 'Thumbnail (optional for YouTube — auto poster from video URL)',
            },
            { name: 'description', type: 'string', label: 'Short Description' },
            { name: 'order', type: 'number', label: 'Display Order' },
          ],
        },
        {
          name: 'image',
          type: 'data',
          folder: 'content/media',
          fields: [
            { name: 'title', type: 'string', label: 'Title' },
            { name: 'type', type: 'enum', options: ['video', 'image'], label: 'Type' },
            { name: 'videoUrl', type: 'string', label: 'Video - YouTube URL' },
            { name: 'imageUrl', type: 'string', label: 'Image - Link URL (opens in new tab)' },
            { name: 'thumbnail', type: 'string', label: 'Thumbnail Image URL' },
            { name: 'description', type: 'string', label: 'Short Description' },
            { name: 'order', type: 'number', label: 'Display Order' },
          ],
        },
        {
          name: 'Role',
          type: 'data',
          folder: 'content/roles',
          fields: [
            { name: 'characterName', type: 'string', label: 'Character' },
            { name: 'operaTitle', type: 'string', label: 'Opera' },
            { name: 'composer', type: 'string', label: 'Composer' },
            { name: 'heroImage', type: 'image', label: 'Hero image' },
            { name: 'summary', type: 'text', label: 'Summary' },
            { name: 'order', type: 'number', label: 'Display order' },
            { name: 'tags', type: 'list', items: { type: 'string' }, label: 'Tags' },
            {
              name: 'appearances',
              type: 'list',
              label: 'Appearances',
              items: {
                type: 'object',
                fields: [
                  { name: 'year', type: 'string', label: 'Year' },
                  { name: 'venue', type: 'string', label: 'Venue' },
                  { name: 'organizationSlug', type: 'string', label: 'Organization slug' },
                  { name: 'city', type: 'string', label: 'City' },
                  { name: 'notes', type: 'string', label: 'Notes' },
                ],
              },
            },
          ],
        },
        {
          name: 'Organization',
          type: 'data',
          folder: 'content/organizations',
          fields: [
            { name: 'name', type: 'string', label: 'Name' },
            { name: 'city', type: 'string', label: 'City' },
            { name: 'country', type: 'string', label: 'Country' },
            { name: 'image', type: 'image', label: 'Image' },
            { name: 'summary', type: 'text', label: 'Summary' },
            { name: 'website', type: 'string', label: 'Website URL' },
            { name: 'order', type: 'number', label: 'Display order' },
          ],
        },
        {
          name: 'ScheduleEvent',
          type: 'data',
          folder: 'content/schedule',
          fields: [
            { name: 'title', type: 'string', label: 'Title' },
            { name: 'subtitle', type: 'string', label: 'Subtitle' },
            { name: 'plot', type: 'text', label: 'Plot (spoiler-free synopsis)' },
            { name: 'composer', type: 'string', label: 'Composer' },
            { name: 'venue', type: 'string', label: 'Venue' },
            { name: 'city', type: 'string', label: 'City' },
            { name: 'image', type: 'image', label: 'Detail image (optional placeholder if empty)' },
            { name: 'imageAlt', type: 'string', label: 'Detail image alt' },
            { name: 'organizationSlug', type: 'string', label: 'Organization slug' },
            { name: 'roleSlug', type: 'string', label: 'Role slug (operatic roles)' },
            {
              name: 'gallerySlug',
              type: 'string',
              label: 'Gallery slug (concerts / no role — match gallery items)',
            },
            { name: 'ticketHref', type: 'string', label: 'Tickets URL (or /contact)' },
            { name: 'badges', type: 'list', items: { type: 'string' }, label: 'Performance dates' },
            {
              name: 'cast',
              type: 'list',
              label: 'Cast',
              items: {
                type: 'object',
                fields: [
                  { name: 'character', type: 'string', label: 'Character' },
                  { name: 'performer', type: 'string', label: 'Performer' },
                ],
              },
            },
            {
              name: 'productionCredits',
              type: 'object',
              label: 'This production',
              fields: [
                { name: 'conductor', type: 'string', label: 'Conductor' },
                { name: 'production', type: 'string', label: 'Production (stage director)' },
                { name: 'setDesigner', type: 'string', label: 'Set designer' },
                { name: 'costumes', type: 'string', label: 'Costumes' },
                { name: 'lighting', type: 'string', label: 'Lighting' },
              ],
            },
            {
              name: 'status',
              type: 'enum',
              label: 'Status',
              options: [
                { label: 'Upcoming', value: 'upcoming' },
                { label: 'Past', value: 'past' },
              ],
            },
            { name: 'year', type: 'string', label: 'Year (past events)' },
            { name: 'order', type: 'number', label: 'Display order' },
          ],
        },
      ],
    }),
  ],
})
