import { defineStackbitConfig } from '@stackbit/types'
import { GitContentSource } from '@stackbit/cms-git'

export default defineStackbitConfig({
  stackbitVersion: '~0.6.0',
  ssgName: 'custom',
  nodeVersion: '22',
  contentSources: [
    new GitContentSource({
      rootPath: __dirname,
      contentDirs: ['content'],
      assetsConfig: {
        referenceType: 'static',
        staticDir: 'public',
        uploadDir: 'images',
        publicPath: '/',
      },
      models: [
        {
          name: 'HomePage',
          type: 'page',
          urlPath: '/',
          filePath: 'content/home/data.md',
          fields: [
            { name: 'instagramUrl', type: 'string', label: 'Social - Instagram URL' },
            { name: 'youtubeUrl', type: 'string', label: 'Social - YouTube URL' },
            { name: 'facebookUrl', type: 'string', label: 'Social - Facebook URL' },
            { name: 'email', type: 'string', label: 'Contact Email' },
          ],
        },
        {
          name: 'AboutPage',
          type: 'page',
          urlPath: '/about',
          filePath: 'content/about/page.md',
          fields: [
            { name: 'heroEyebrow', type: 'string', label: 'Hero — Eyebrow' },
            { name: 'heroTitleLine1', type: 'string', label: 'Hero — Title line 1' },
            { name: 'heroTitleAccent', type: 'string', label: 'Hero — Accent word' },
            { name: 'heroTitleLine2', type: 'string', label: 'Hero — Title line 2' },
            { name: 'heroIntro', type: 'text', label: 'Hero — Intro paragraph' },
            {
              name: 'heroImage',
              type: 'image',
              label: 'Hero — Portrait (optional; uses home About image if empty)',
            },
            { name: 'heroImageAlt', type: 'string', label: 'Hero — Image alt' },
            { name: 'heroQuote', type: 'text', label: 'Hero — Quote' },
            { name: 'heroQuoteAttribution', type: 'string', label: 'Hero — Quote attribution' },
            {
              name: 'highlights',
              type: 'list',
              label: 'Stats row',
              items: {
                type: 'object',
                fields: [
                  { name: 'number', type: 'string', label: 'Number' },
                  { name: 'label', type: 'string', label: 'Label' },
                ],
              },
            },
            { name: 'fullBioEyebrow', type: 'string', label: 'Bio section — Eyebrow' },
            {
              name: 'fullBioParagraphs',
              type: 'list',
              label: 'Bio — Paragraphs',
              items: { type: 'text' },
            },
            { name: 'timelineSectionEyebrow', type: 'string', label: 'Timeline — Eyebrow' },
            { name: 'timelineSectionTitle', type: 'string', label: 'Timeline — Title' },
            {
              name: 'timeline',
              type: 'list',
              label: 'Timeline — Milestones',
              items: {
                type: 'object',
                fields: [
                  { name: 'year', type: 'string', label: 'Year' },
                  { name: 'title', type: 'string', label: 'Title' },
                  { name: 'description', type: 'text', label: 'Description' },
                ],
              },
            },
            { name: 'ctaTitleLine1', type: 'string', label: 'CTA — Title line 1' },
            { name: 'ctaTitleLine2', type: 'string', label: 'CTA — Title line 2' },
            { name: 'ctaPrimaryLabel', type: 'string', label: 'CTA — Primary button' },
            { name: 'ctaPrimaryHref', type: 'string', label: 'CTA — Primary URL' },
            { name: 'ctaSecondaryLabel', type: 'string', label: 'CTA — Secondary button' },
            { name: 'ctaSecondaryHref', type: 'string', label: 'CTA — Secondary URL' },
          ],
        },
        {
          name: 'ProductionsPage',
          type: 'page',
          urlPath: '/productions',
          filePath: 'content/productions-landing/page.md',
          fields: [
            { name: 'heroEyebrow', type: 'string', label: 'Hero — Eyebrow' },
            { name: 'heroTitle', type: 'string', label: 'Hero — Title' },
            { name: 'heroIntro', type: 'text', label: 'Hero — Intro' },
          ],
        },
        {
          name: 'GalleryPage',
          type: 'page',
          urlPath: '/gallery',
          filePath: 'content/gallery-landing/page.md',
          fields: [
            { name: 'heroEyebrow', type: 'string', label: 'Hero — Eyebrow' },
            { name: 'heroTitle', type: 'string', label: 'Hero — Title' },
            {
              name: 'filterCategories',
              type: 'list',
              label: 'Filter tabs (first should be “All”)',
              items: { type: 'string' },
            },
          ],
        },
        {
          name: 'ContactPage',
          type: 'page',
          urlPath: '/contact',
          filePath: 'content/contact/page.md',
          fields: [
            { name: 'heroEyebrow', type: 'string', label: 'Hero — Eyebrow' },
            { name: 'heroTitle', type: 'string', label: 'Hero — Title' },
            { name: 'introHeading', type: 'string', label: 'Intro — Heading' },
            { name: 'introBody', type: 'text', label: 'Intro — Body' },
            { name: 'directEmailLabel', type: 'string', label: 'Email block — Label' },
            { name: 'socialChannelsLabel', type: 'string', label: 'Social — Section label' },
            { name: 'instagramHandle', type: 'string', label: 'Social — Instagram display' },
            { name: 'youtubeHandle', type: 'string', label: 'Social — YouTube display' },
            { name: 'facebookHandle', type: 'string', label: 'Social — Facebook display' },
            { name: 'successTitle', type: 'string', label: 'Form success — Title' },
            { name: 'successMessage', type: 'text', label: 'Form success — Message' },
            { name: 'successResetLabel', type: 'string', label: 'Form success — Reset link' },
          ],
        },
        {
          name: 'HomeSections',
          type: 'data',
          filePath: 'content/home/sections.md',
          fields: [
            {
              name: 'sections',
              type: 'json',
              label: 'Homepage sections (ordered)',
              description:
                'Array of blocks: type hero | about_teaser | media_grid | feature_split | quote_banner. Reorder to change layout.',
            },
          ],
        },
        {
          name: 'GalleryItem',
          type: 'data',
          folder: 'content/gallery',
          fields: [
            { name: 'title', type: 'string', label: 'Title' },
            { name: 'image', type: 'string', label: 'Image URL' },
            { name: 'alt', type: 'string', label: 'Alt Text (accessibility)' },
            { name: 'category', type: 'string', label: 'Category (Performance / Behind the Scenes)' },
            { name: 'order', type: 'number', label: 'Display Order' },
          ],
        },
        {
          name: 'video',
          type: 'data',
          folder: 'content/media',
          fields: [
            { name: 'title', type: 'string', label: 'Title' },
            { name: 'type', type: 'enum', options: ['video', 'image'], label: 'Type' },
            { name: 'videoUrl', type: 'string', label: 'Video - YouTube Embed URL' },
            { name: 'thumbnail', type: 'string', label: 'Thumbnail Image URL' },
            { name: 'description', type: 'string', label: 'Short Description' },
            { name: 'order', type: 'number', label: 'Display Order' },
          ],
        },
        {
          name: 'image',
          type: 'data',
          folder: 'content/media',
          fields: [
            { name: 'title', type: 'string', label: 'Title' },
            { name: 'type', type: 'enum', options: ['video', 'image'], label: 'Type' },
            { name: 'videoUrl', type: 'string', label: 'Video - YouTube Embed URL' },
            { name: 'thumbnail', type: 'string', label: 'Thumbnail Image URL' },
            { name: 'description', type: 'string', label: 'Short Description' },
            { name: 'order', type: 'number', label: 'Display Order' },
          ],
        },
        {
          name: 'Production',
          type: 'data',
          folder: 'content/productions',
          fields: [
            { name: 'title', type: 'string', label: 'Opera Title' },
            { name: 'role', type: 'string', label: 'Role / Character' },
            { name: 'venue', type: 'string', label: 'Venue & City' },
            { name: 'year', type: 'string', label: 'Year' },
            { name: 'image', type: 'string', label: 'Production Image URL' },
            { name: 'description', type: 'text', label: 'Description' },
            { name: 'tags', type: 'list', items: { type: 'string' }, label: 'Tags' },
          ],
        },
        {
          name: 'Education',
          type: 'data',
          folder: 'content/education',
          fields: [
            { name: 'school', type: 'string', label: 'School' },
            { name: 'summary', type: 'string', label: 'Summary' },
            { name: 'startDate', type: 'string', label: 'Start Date' },
            { name: 'endDate', type: 'string', label: 'End Date' },
            { name: 'tags', type: 'list', items: { type: 'string' }, label: 'Tags' },
          ],
        },
      ],
    }),
  ],
})
